# Generated by Django 4.2.4 on 2024-02-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_customuser_is_staff_customuser_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usercode',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
